"""Add notice and event management fields

Revision ID: 2e689ecb726e
Revises: d60779e4f674
Create Date: 2026-08-10 13:41:01.049295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e689ecb726e'
down_revision: Union[str, Sequence[str], None] = 'd60779e4f674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('registration_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('notices', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('notices', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('notices', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('notices', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'updated_at')
    op.drop_column('notices', 'expires_at')
    op.drop_column('notices', 'published_at')
    op.drop_column('notices', 'priority')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'published')
    op.drop_column('events', 'registration_url')
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
