"""Add image and document uploads

Revision ID: 6716c2725144
Revises: 9110ffb69dad
Create Date: 2026-08-12 23:35:06.594989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6716c2725144'
down_revision: Union[str, Sequence[str], None] = '9110ffb69dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('document_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'document_url')
    # ### end Alembic commands ###
