"""Add image and document fields to notices

Revision ID: 9110ffb69dad
Revises: 31668f6aece7
Create Date: 2026-08-12 23:24:29.934683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9110ffb69dad'
down_revision: Union[str, Sequence[str], None] = '31668f6aece7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('notices', sa.Column('document_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'document_url')
    op.drop_column('notices', 'image_url')
    # ### end Alembic commands ###
